name: tda-dev
dependencies:
- python=3
- cython
- pandas
- requests
- pylint
- spyder
- openpyxl
- xlrd
- xlsxwriter
- matplotlib
- scikit-learn
- plotly
- pip
- pytest
- pytest-cov
- twine

- pip:
  - python-dotenv
