name: tda-dev
dependencies:
- python=3
- cython
- pandas
- requests
- pylint
- spyder
- openpyxl
- xlrd
- xlsxwriter
- matplotlib
- scikit-learn
- pip
- plotly
- plotly::plotly-orca
- poppler
- psutil
- pytest
- pytest-cov

- pip:
  - python-dotenv